### ISSUE TITLE
env: node\r: No such file or directory

### ISSUE THREAD

**Issue by bfintal** [ConquestArrow/dtsmake#6]
Having this error in Mac when I run dtsmake.

Doing `:set ff=unix` fixes it.

**Comment by dually8** [comment]
I get that error regardless on macOS. Tried changing the file format/line endings to no avail.

**Comment by ConquestArrow** [comment]
Thanks @bfintal @dually8 , I fixed it.
https://github.com/ConquestArrow/dtsmake/releases/tag/v0.0.10
